services:
  - type: web
    name: rrive-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: AUTH0_MGMT_API_TOKEN
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false