from app.agent.planner import decide_action
from app.agent.tools import execute_tool
from app.services.ai_service import generate_text
from app.agent.memory import get_memory, add_to_memory, get_session, update_session
from app.auth.token_vault import get_google_token


def handle_user_query(message: str, user: dict, refresh_token: str = None):
    """
    Process a user message and decide how to respond.
    Either call a tool (like GitHub or Drive) or generate an AI reply.
    Save the conversation history and session state for later use.
    """

    user_id = user.get("sub", "default_user")

    google_token = get_google_token(refresh_token)

    add_to_memory(user_id, "user", message)
    history = get_memory(user_id)
    session = get_session(user_id)

    action = decide_action(message, history)

    if isinstance(action, list):
        action = action[0] if action else {"type": "ai"}
    if not isinstance(action, dict):
        action = {"type": "ai"}

    
    # TOOL EXECUTION
    if action.get("type") == "tool":
        tool_name = action.get("tool")

        if message.lower() in ["show more", "more", "next"]:
            tool_input = session.get("query")
            page = session.get("page", 1) + 1
            if not tool_input:
                tool_input = message.lower()
                page = 1
        else:
            # For summarize_repo - preserve owner/repo format like "facebook/react"
            if tool_name == "summarize_repo":
                tool_input = action.get("input", message).strip()
            else:
                words = message.lower().split()
                stopwords = [
                    "show", "me", "repos", "repositories",
                    "repository", "find", "search", "give"
                ]
                keywords = [w for w in words if w not in stopwords]
                tool_input = " ".join(keywords).strip()
                if not tool_input:
                    tool_input = message.lower()
            page = 1

        update_session(user_id, {
            "query": tool_input,
            "page": page,
            "tool": tool_name
        })

        if not google_token and tool_name in ["drive_search", "save_summary"]:
            return {
                "type": "text",
                "data": "Google Drive not available. Please login with Google."
            }

        # For save_summary - show auth_required first, don't execute yet
        if tool_name == "save_summary":
            # Check if there's a stored summary to save
            last_summary = session.get("last_summary")
            if not last_summary:
                return {
                    "type": "text",
                    "data": "No summary found. Please summarize a repository first, then say 'save to drive'."
                }
            return {"type": "auth_required", "data": last_summary}

        tool_result = execute_tool(
            tool_name,
            tool_input,
            page,
            google_token,
            user_id
        )

        add_to_memory(user_id, "assistant", str(tool_result))

        if tool_name == "github_search":
            return {"type": "repos", "data": tool_result}

        elif tool_name == "summarize_repo":
            # Store summary in session for later Drive save
            update_session(user_id, {
                "query": tool_input,
                "page": page,
                "tool": tool_name,
                "last_summary": tool_result
            })
            return {"type": "text", "data": tool_result}

    
    # AI RESPONSE
    elif action.get("type") == "ai":
        context = "\n".join([
            f"{msg['role']}: {msg['content']}" for msg in history
        ])

        prompt = f"""
        Conversation so far:
        {context}

        User: {message}
        Assistant:
        """

        answer = generate_text(prompt)
        add_to_memory(user_id, "assistant", answer)

        # for ai summary saving of answers
        update_session(user_id, {
            "query": message,
            "page": 1,
            "tool": "ai",
            "last_summary": answer 
        })

        return {"type": "text", "data": answer}

    return {"type": "text", "data": "Unable to process request."}


def handle_save_to_drive(user_id: str, refresh_token: str = None):
    """
    Saves a previously generated summary into Google Drive.
    Called when the user clicks Approve in the chat UI.
    Needs a valid Google token, generated by AuthO Token Vault and a stored summary from the session.
    """

    google_token = get_google_token(refresh_token)

    if not google_token:
        return {"type": "text", "data": " Google Drive not available."}

    # Get stored summary from session
    session = get_session(user_id)
    last_summary = session.get("last_summary")

    if not last_summary:
        return {
            "type": "text",
            "data": " No summary found to save. Please summarize a repository first."
        }

    result = execute_tool("save_summary", last_summary, 1, google_token, user_id)
    return {"type": "text", "data": result}